app:
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/umbrella
  ports:
    - 4040:4040

web:
  extends: app
  environment:
    - USER
    - USERNAME
    - MIX_ENV=dev
    - PG_HOST=db
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
  links:
    - db

tests:
  extends: app
  command: mix do coveralls
  environment:
    - USER
    - USERNAME
    - MIX_ENV=test
    - PG_HOST=db
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
  links:
    - db

db:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432